### PR TITLE
Update README.mkdn

### PR DESCRIPTION
**Pull request by Dearmw**
--depth=1

### CODE REVIEW

**Comment by cm-gerrit** [comment]
Hi there;

This is an automated reply, to let you know CyanogenMod doesn't merge pull
requests submitted directly to our github.com repositories.

You can submit your change requests through our public review system,
located at http://review.cyanogenmod.org/

That review system is an installation of Google's Gerrit code review.
If you've never interacted with Gerrit before, we also suggest you take
a look at http://wiki.cyanogenmod.org/wiki/Howto:_Gerrit

Thanks!

**Comment by JulianVolodia** [comment]
Is it not merged?

**Comment by Caio99BR** [comment]
You need to use CyanogenMod Review <review.cyanogenmod.org>

Em sex, 7 de out de 2016 07:28, Volodia notifications@github.com escreveu:

**Comment by neobuddy89** [comment]
lol.

**Comment by JulianVolodia** [comment]
@Caio99BR wut? :)

**Pull request closed without merging**
