### PR TITLE
Remove svox due to DMCA takedown

### PR DESCRIPTION
**Pull request by jmorvan**
prevents repo sync

### CODE REVIEW

**Comment by OctoGerrit** [comment]
https://github.com/CyanogenMod/android/blob/cm-12.0/default.xml#L306

SVOX is being pulled from Google directly since the takedown.  Update your manifest.

**Comment by fonz93** [comment]
@OctoGerrit manifest was been updated only on CM11 and CM12

**Comment by fonz93** [comment]
@OctoGerrit the official CyanogenMod manifest was been updated only on CM11 and CM12

**Comment by OctoGerrit** [comment]
@fonz93 Didn't even see this was JB - but, still needs to be updated rather than commented out.  Thanks for the heads-up on that!

**Comment by jmorvan** [comment]
Ok I guess https://github.com/CyanogenMod/android/pull/49 will handle this.

**Comment by fonz93** [comment]
@jmorvan Yes, it does, atleast on CM10.1, choose the correct branch from AOSP for the "jellybean" branch

**Pull request closed without merging**
